DATA:
  classes: null
  clip: 0.005
  data_path: ../../contact_graspnet/checkpoints/acronym
  gripper_width: 0.08
  input_normals: false
  intrinsics: realsense
  labels:
    bin_weights:
    - 0.16652107
    - 0.21488856
    - 0.37031708
    - 0.55618503
    - 0.75124664
    - 0.93943357
    - 1.07824539
    - 1.19423112
    - 1.55731375
    - 3.17161779
    contact_gather: knn
    filter_z: true
    k: 1
    max_radius: 0.005
    min_unique_pos_contacts: 1
    num_neg_contacts: 0
    num_pos_contacts: 10000
    offset_bins:
    - 0
    - 0.00794435329
    - 0.0158887021
    - 0.0238330509
    - 0.0317773996
    - 0.0397217484
    - 0.0476660972
    - 0.055610446
    - 0.0635547948
    - 0.0714991435
    - 0.08
    to_gpu: false
    z_val: -0.1
  ndataset_points: 20000
  num_point: 2048
  num_test_scenes: 1000
  raw_num_points: 20000
  sigma: 0.001
  train_and_test: false
  train_on_scenes: true
  use_farthest_point: false
  use_uniform_quaternions: false
LOSS:
  max_geom_loss_divisor: 100.0
  min_geom_loss_divisor: 1.0
  offset_loss_type: sigmoid_cross_entropy
  too_small_offset_pred_bin_factor: 0
  topk_confidence: 512
MODEL:
  asymmetric_model: true
  bin_offsets: true
  contact_distance_offset: true
  dir_vec_length_offset: false
  grasp_conf_head:
    conv1d: 1
    dropout_keep: 0.5
  grasp_dir_head:
    conv1d: 3
    dropout_keep: 0.7
  joint_head:
    conv1d: 4
    dropout_keep: 0.7
  joint_heads: false
  larger_model: false
  model: contact_graspnet
  pointnet_fp_modules:
  - mlp:
    - 256
    - 256
  - mlp:
    - 256
    - 128
  - mlp:
    - 128
    - 128
    - 128
  pointnet_sa_module:
    group_all: true
    mlp:
    - 256
    - 512
    - 1024
  pointnet_sa_modules_msg:
  - mlp_list:
    - - 32
      - 32
      - 64
    - - 64
      - 64
      - 128
    - - 64
      - 96
      - 128
    npoint: 2048
    nsample_list:
    - 32
    - 64
    - 128
    radius_list:
    - 0.02
    - 0.04
    - 0.08
  - mlp_list:
    - - 64
      - 64
      - 128
    - - 128
      - 128
      - 256
    - - 128
      - 128
      - 256
    npoint: 512
    nsample_list:
    - 64
    - 64
    - 128
    radius_list:
    - 0.04
    - 0.08
    - 0.16
  - mlp_list:
    - - 64
      - 64
      - 128
    - - 128
      - 128
      - 256
    - - 128
      - 128
      - 256
    npoint: 128
    nsample_list:
    - 64
    - 64
    - 128
    radius_list:
    - 0.08
    - 0.16
    - 0.32
  pred_contact_approach: true
  pred_contact_base: true
  pred_contact_offset: true
  pred_contact_success: true
  pred_grasps_adds: false
  pred_grasps_adds_gt2pred: false
OPTIMIZER:
  adds_gt2pred_loss_weight: 1
  adds_loss_weight: 10
  approach_cosine_loss_weight: 1
  batch_size: 14
  bn_decay_clip: 0.99
  bn_decay_decay_rate: 0.5
  bn_decay_decay_step: 200000
  bn_init_decay: 0.5
  decay_rate: 0.7
  decay_step: 200000
  dir_cosine_loss_weight: 1
  learning_rate: 0.001
  max_epoch: 16
  momentum: 0.9
  offset_loss_weight: 1
  optimizer: adam
  score_ce_loss_weight: 1
TEST:
  allow_zero_margin: 0
  bin_vals: max
  center_to_tip: 0.0
  extra_opening: 0.005
  filter_thres: 0.0001
  first_thres: 0.23
  max_farthest_points: 150
  num_samples: 200
  save: false
  scale_fac:
  - 1.25
  - 1.0
  - 0.75
  - 0.5
  scales: false
  second_thres: 0.18
  with_replacement: false
